// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlgoMainStat } from "../enums/AlgoMainStat";
import type { Algorithm } from "../enums/Algorithm";

export interface AlgoPiece { name: Algorithm, stat: AlgoMainStat, slot: Array<boolean>, }