// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlgoCategory } from "../enums/AlgoCategory";
import type { Algorithm } from "../enums/Algorithm";

export interface AlgoTypeDb { category: AlgoCategory, algos: Array<Algorithm>, }