// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlgoPiece } from "./AlgoPiece";

export interface AlgoSet { offense: Array<AlgoPiece>, stability: Array<AlgoPiece>, special: Array<AlgoPiece>, }