// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coin } from "./Coin";
import type { Exp } from "./Exp";
import type { SkillCurrency } from "./SkillCurrency";
import type { WidgetResource } from "./WidgetResource";

export interface GrandResource { skill: SkillCurrency, coin: Coin, widgets: Array<WidgetResource>, exp: Exp, neural_kits: number, }