// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Keychain } from "./Keychain";

export interface KeychainTable { keychains: Array<Keychain>, }