// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlgoSet } from "./AlgoSet";
import type { Level } from "./Level";
import type { NeuralExpansion } from "../enums/NeuralExpansion";
import type { NeuralFragment } from "./NeuralFragment";
import type { UnitSkill } from "./UnitSkill";

export interface Loadout { skill_level: UnitSkill, level: Level, algo: AlgoSet, neural: NeuralExpansion, frags: NeuralFragment, }