// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coin } from "./Coin";
import type { NeuralFragment } from "./NeuralFragment";

export interface NeuralResourceRequirement { frags: NeuralFragment, coin: Coin, kits: number, }