// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coin } from "./Coin";

export interface NeuralResourceRequirement { frags: number, coin: Coin, }