// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlotPlacement } from "..\\enums\\SlotPlacement";

export interface Slot { placement: SlotPlacement, value: boolean, }