// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Class } from "..\\enums\\Class";
import type { Loadout } from "./Loadout";

export interface Unit { name: string, class: Class, current: Loadout, goal: Loadout, }