// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Database } from "./Database";
import type { Unit } from "./Unit";

export interface UserJSON { $schema: string, database: Database, units: Array<Unit>, }