// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coin } from "./Coin";
import type { WidgetResource } from "./WidgetResource";

export interface WidgetResourceRequirement { widget: WidgetResource, coin: Coin, }