// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "err", input: never, result: string } | 
        { key: "getUnitFromId", input: string, result: Unit } | 
        { key: "getUnits", input: never, result: Array<Unit> } | 
        { key: "listLoadoutType", input: never, result: Array<LoadoutType> } | 
        { key: "loadoutByUnitId", input: string, result: Array<Loadout> } | 
        { key: "loadouts", input: string | null, result: Array<Loadout> } | 
        { key: "skillLevelsByUnitIds", input: Array<string> | null, result: Array<UnitSkill> } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "deleteUnit", input: string, result: Unit } | 
        { key: "newUnit", input: [string, Class], result: Unit },
    subscriptions: never
};

export type Class = "Guard" | "Medic" | "Sniper" | "Specialist" | "Warrior"

export interface Loadout { id: string, level: number, neural: string, frags: number | null, loadoutType: string, unitId: string }

export type LoadoutType = "Current" | "Goal"

export interface Unit { id: string, name: string, class: string }

export interface UnitSkill { id: string, auto: number, passive: number, loadoutId: string }
