// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "algoPieces.get", input: never, result: Array<AlgoPiece> } | 
        { key: "algoPieces.getByLoadoutIds", input: Array<string>, result: Array<AlgoPiece> } | 
        { key: "displayAlgoMainstat", input: never, result: Array<AlgoMainStat> } | 
        { key: "enum.pretty.Algorithm", input: never, result: Array<Algorithm> } | 
        { key: "enum.pretty.Algorithm.toRaw", input: string, result: string } | 
        { key: "enum.pretty.LoadoutType", input: never, result: Array<LoadoutType> } | 
        { key: "enum.pretty.LoadoutType.raw", input: string, result: string } | 
        { key: "enum.rust.Algorithm", input: never, result: Array<string> } | 
        { key: "enum.rust.LoadoutType", input: never, result: Array<string> } | 
        { key: "listAlgoMainstat", input: Array<AlgoMainStat> | null, result: Array<string> } | 
        { key: "loadout.getByUnitId", input: string | null, result: Array<Loadout> } | 
        { key: "loadouts.get", input: never, result: Array<Loadout> } | 
        { key: "loadouts.getById", input: string, result: Array<Loadout> } | 
        { key: "requirements.algos", input: never, result: Array<AlgorithmRequirement> } | 
        { key: "slots.get", input: never, result: Array<Slot> } | 
        { key: "slots.getByAlgoPieceIds", input: Array<string> | null, result: Array<Slot> } | 
        { key: "unit.getById", input: string, result: Unit } | 
        { key: "unitSkills.get", input: never, result: Array<UnitSkill> } | 
        { key: "unitSkills.getByUnitIds", input: Array<string>, result: Array<UnitSkill> } | 
        { key: "units.get", input: never, result: Array<Unit> } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "algoPiece.deleteById", input: string, result: AlgoPiece } | 
        { key: "algoPiece.new", input: [string | null, AlgoCategory, boolean], result: AlgoPiece } | 
        { key: "algoPieces.save", input: Array<AlgoPiece>, result: Array<AlgoPiece> } | 
        { key: "loadouts.save", input: Array<Loadout>, result: Array<Loadout> } | 
        { key: "slots.save", input: Array<Slot>, result: Array<Slot> } | 
        { key: "unit.delete", input: string, result: Unit } | 
        { key: "unit.new", input: [string, Class], result: Unit } | 
        { key: "unitSkills.save", input: Array<UnitSkill>, result: Array<UnitSkill> } | 
        { key: "units.save", input: Array<Unit>, result: Array<Unit> },
    subscriptions: never
};

export type AlgoCategory = "Offense" | "Stability" | "Special"

export type AlgoMainStat = "Hashrate" | "HashratePercent" | "Atk" | "AtkPercent" | "Health" | "HealthPercent" | "Haste" | "PhysPen" | "PhysPenPercent" | "OperandPen" | "OperandPenPercent" | "CritRate" | "CritDmg" | "DamageInc" | "Dodge" | "HealInc" | "Def" | "DefPercent" | "OperandDef" | "OperandDefPercent" | "PostBattleRegen"

export interface AlgoPiece { id: string, category: string, name: string, stat: string, loadoutId: string | null }

export type Algorithm = "LowerLimit" | "Feedforward" | "Deduction" | "Progression" | "DataRepair" | "MLRMatrix" | "Stack" | "LimitValue" | "Encapsulate" | "Iteration" | "Perception" | "Overflow" | "Rationality" | "Connection" | "Convolution" | "Reflection" | "Resolve" | "Inspiration" | "LoopGain" | "SVM" | "Paradigm" | "DeltaV" | "Cluster" | "Stratagem" | "Exploit"

export interface AlgorithmRequirement { pieces: Array<IAlgoPiece>, from_unit: IUnit }

export type Class = "Guard" | "Medic" | "Sniper" | "Specialist" | "Warrior"

export interface IAlgoPiece { name: Algorithm, stat: AlgoMainStat, category: AlgoCategory, slot: IAlgoSlot }

export interface IAlgoSet { offense: Array<IAlgoPiece>, stability: Array<IAlgoPiece>, special: Array<IAlgoPiece> }

export type IAlgoSlot = Array<ISlot>

export type ILevel = number

export interface ILoadout { skill_level: IUnitSkill, level: ILevel, algo: IAlgoSet, neural: NeuralExpansion, frags: INeuralFragment, loadout_type: LoadoutType }

export type INeuralFragment = number | null

export interface ISlot { placement: SlotPlacement, value: boolean }

export interface IUnit { name: string, class: Class, current: ILoadout, goal: ILoadout }

export interface IUnitSkill { passive: number, auto: number }

export interface Loadout { id: string, level: number, neural: string, frags: number | null, loadoutType: string, unitId: string }

export type LoadoutType = "Current" | "Goal"

export type NeuralExpansion = "One" | "OneHalf" | "Two" | "TwoHalf" | "Three" | "ThreeHalf" | "Four" | "FourHalf" | "Five"

export interface Slot { id: string, placement: string, value: boolean, algoPieceId: string }

export type SlotPlacement = "One" | "Two" | "Three"

export interface Unit { id: string, name: string, class: string }

export interface UnitSkill { id: string, auto: number, passive: number, loadoutId: string }
