// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "units", input: never, result: Array<{ id: string, name: string, class: string, className: string, currentLoadoutId: string, goalLoadoutId: string, current: Loadout, goal: Loadout }> } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};

export interface Loadout { id: string, level: number, neural: string, frags: number | null, loadoutType: string, unitSkillId: string }
