// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlgoMainStat = "Hashrate" | "HashratePercent" | "Atk" | "AtkPercent" | "Health" | "HealthPercent" | "Haste" | "CritRate" | "CritDmg" | "DamageInc" | "Dodge" | "HealInc" | "DamageReduction" | "Def" | "DefPercent" | "OperandDef" | "OperandDefPercent";