// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Class } from "./Class";

export type Bonus = "Coin" | "Exp" | "Skill" | { Class: Class };